<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
		<PackageReference Include="Microsoft.AspNetCore.JsonPatch" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
		<PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" />
		<PackageReference Include="Scalar.AspNetCore" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\HrmSystem.Application\HrmSystem.Application.csproj" />
		<ProjectReference Include="..\..\Infrastructure\HrmSystem.Infrastructure\HrmSystem.Infrastructure.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<!-- -> -> -> We Have these in: `Directory.Build.props` <- <- <- -->
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
	</PropertyGroup>

</Project>
