using HrmSystem.Application.Common.Interfaces.Reporting;
using HrmSystem.Application.Features.Analytics.Shared;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace HrmSystem.Infrastructure.Services.Export;

/*
    //?     PDF rendering of the dashboard export via QuestPDF (fluent layout, tables — no
    //?     headless browser). Charts are represented as tables in Phase 1.
    //!     LICENSE: QuestPDF Community is free only below $1M USD annual revenue — a
    //!     commercial SaaS must buy a license (docs/architecture.md). Swappable behind
    //!     IAnalyticsReportRenderer by design.
*/
internal sealed class PdfAnalyticsReportRenderer : IAnalyticsReportRenderer
{
    static PdfAnalyticsReportRenderer()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public string Format => "pdf";

    public ExportedReport Render(AnalyticsReportModel model)
    {
        byte[] pdf = Document
            .Create(container =>
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(36);
                    page.DefaultTextStyle(style => style.FontSize(10));

                    page.Header()
                        .Column(header =>
                        {
                            header.Item().Text($"{model.CompanyName} — HR Analytics Report")
                                .FontSize(16)
                                .Bold();
                            header.Item().Text($"Period: {model.From:yyyy-MM-dd} → {model.To:yyyy-MM-dd}")
                                .FontColor(Colors.Grey.Darken1);
                        });

                    page.Content()
                        .PaddingVertical(12)
                        .Column(content =>
                        {
                            content.Spacing(14);

                            content.Item().Element(c => RenderSummary(c, model.Summary));
                            content.Item().Element(c =>
                                RenderCategoryTable(c, "Employees per Department", model.DepartmentDistribution)
                            );
                            content.Item().Element(c =>
                                RenderCategoryTable(c, "Leave Requests by Type", model.LeaveStats.ByType)
                            );
                            content.Item().Element(c =>
                                RenderCategoryTable(c, "Leave Requests by Status", model.LeaveStats.ByStatus)
                            );
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated by HrmSystem — page ");
                            text.CurrentPageNumber();
                            text.Span(" of ");
                            text.TotalPages();
                        });
                })
            )
            .GeneratePdf();

        return new ExportedReport(
            pdf,
            "application/pdf",
            $"analytics-report_{model.From:yyyyMMdd}-{model.To:yyyyMMdd}.pdf"
        );
    }

    private static void RenderSummary(IContainer container, KpiSummary summary)
    {
        container.Column(column =>
        {
            column.Item().Text("Key Metrics").FontSize(12).Bold();
            column.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(3);
                    columns.RelativeColumn(1);
                });

                AddRow(table, "Total Employees", summary.TotalEmployees);
                AddRow(table, "Present Today", summary.PresentToday);
                AddRow(table, "Late Today", summary.LateToday);
                AddRow(table, "Absent Today", summary.AbsentToday);
                AddRow(table, "Pending Leaves", summary.PendingLeaves);
                AddRow(table, "Departments", summary.Departments);
            });
        });
    }

    private static void RenderCategoryTable(
        IContainer container,
        string title,
        IReadOnlyList<CategoryCount> items
    )
    {
        container.Column(column =>
        {
            column.Item().Text(title).FontSize(12).Bold();
            column.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(3);
                    columns.RelativeColumn(1);
                });

                foreach (CategoryCount item in items)
                {
                    AddRow(table, item.Label, item.Value);
                }
            });
        });
    }

    private static void AddRow(TableDescriptor table, string label, int value)
    {
        table.Cell().BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(3).Text(label);
        table.Cell()
            .BorderBottom(0.5f)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(3)
            .AlignRight()
            .Text($"{value}");
    }
}
